### ISSUE TITLE
Dashboard: Add a member manually in on-chain groups only if it was not added before

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#302]

**Comment by tanyas-codes** [comment]
Hey @vplasencia ,i solved the bug successfully ! 

Below are the snapshots which show the working before and after the changes :
Before the changes a user can add same id to an an on-chain group(which shouldnt be the case because of duplicacy) :
<img width="1440" alt="bug" src="https://github.com/privacy-scaling-explorations/bandada/assets/107319582/74d255c3-f52f-435f-92e2-2e7822110e45">

After making the changes:-user cannot add the same id ,an alert is poppped up saying "member already exists"


https://github.com/privacy-scaling-explorations/bandada/assets/107319582/8a79f569-d248-4132-829e-71d4c7f99619

**Comment by vplasencia** [comment]
Hey @tanyas-codes 

Wow, it looks great! Thank you so much. Do you want me to assign you this issue?

**Comment by tanyas-codes** [comment]
Yes ,please do assign the issue ! 

Following up ,The bug is solved succesfully but i came across another corner case/issue (another bug) 
Basically if an user enters an hexadecimal member id ,it is added to the list and once it is it is changed to decimal .
Now if i add the same hexacedimal id ,it accepts the id (which it shouldnt ).
below is the recording of how this other issue arises :

https://github.com/privacy-scaling-explorations/bandada/assets/107319582/cb98c16f-3b29-4f1e-92dd-4442b1a8fc33

So should i let users enter hexa values but then throw an error?because ultimately the hexa values are converted into decimals !

**Comment by tanyas-codes** [comment]
okay ,ill make the required changes !

**Comment by tanyas-codes** [comment]
@vplasencia Done! Attaching a video of how it works now if user enters an hexa value! 

I'll make the PR now?

https://github.com/privacy-scaling-explorations/bandada/assets/107319582/f79bc1e5-280a-4eca-ada3-2748b3f2c95d

**Comment by vplasencia** [comment]
It looks great @tanyas-codes. Yes, feel free to create the PR. Thank you so much.
